apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: api-db-password
  namespace: demo
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: aws-store
    kind: SecretStore
  target:
    name: api-db-secret
    creationPolicy: Owner
  data:
  - secretKey: DB_PASSWORD
    remoteRef:
      key: w10/demo/db-password
      property: DB_PASSWORD
