apiVersion: v1
kind: Pod
metadata:
  name: secret-reader
  namespace: demo
  labels:
    app: secret-reader
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  securityContext:
    runAsUser: 1000
  containers:
  - name: reader
    image: ghcr.io/phuc776/w10-api:0.0.1
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh", "-c"]
    args:
    - |
      while true; do
        date
        cat /etc/db-secret/DB_PASSWORD
        sleep 10
      done
    resources:
      limits:
        cpu: 100m
        memory: 64Mi
    volumeMounts:
    - name: db-secret
      mountPath: /etc/db-secret
      readOnly: true
  volumes:
  - name: db-secret
    secret:
      secretName: api-db-secret
