apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: require-phuc776-signature
spec:
  mode: enforce
  images:
  - glob: ghcr.io/phuc776/w10-api**
  authorities:
  - name: authority-0
    key:
      hashAlgorithm: sha256
      data: |
        -----BEGIN PUBLIC KEY-----
        MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEtLoOTsA41m4jp+rur5suDJe5+ysC
        rVsjN/55EOzkrThA0CzggtqdHpP0/IpANdQ6fgMHnEbmzwZfs2U0VL5Fhg==
        -----END PUBLIC KEY-----
