apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: require-phuc776-signature
spec:
  images:
  - glob: ghcr.io/phuc776/w10-api**
  authorities:
  - key:
      hashAlgorithm: sha256
      data: |
        -----BEGIN PUBLIC KEY-----
        MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEbOHWBCCFgHHsBq4kj7B4Jfy3h503
        9xUGdWSIvqHTTwILDHcI2jmXF8gUVUQMf8t8U9x6M/odEn+sQPcio1Csfw==
        -----END PUBLIC KEY-----
